AllCops:
  Exclude:
    - "spec/tmp/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
Security/Eval:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/HashSyntax:
  Enabled: true
Layout/EndOfLine:
  EnforcedStyle: native
